version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: dev_postgres
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Initialization script (optional)

volumes:
  postgres_data: